#include "midi/MidiFileIO.h"
#include "midi/MidiFixtures.h"
#include "research/Fixtures.h"
#include "support/TestHelpers.h"

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include <set>

using Catch::Approx;
using namespace osp;

namespace
{
    std::vector<MidiEvent> notesOn (const MidiSequence& seq)
    {
        std::vector<MidiEvent> out;
        for (const auto& e : seq.events)
            if (e.type == MidiEvent::Type::noteOn)
                out.push_back (e);
        return out;
    }
}

TEST_CASE ("fixtures: definitions match the specification", "[unit][midi]")
{
    const auto rep = notesOn (fixtures::repetition (60));
    REQUIRE (rep.size() == 8);
    for (const auto& e : rep)
    {
        CHECK (e.note == 60);
        CHECK (e.value == 90);
    }

    const auto dyn = notesOn (fixtures::dynamics (57));
    REQUIRE (dyn.size() == 6);
    const int velocities[] = { 20, 40, 60, 80, 100, 127 };
    for (std::size_t i = 0; i < 6; ++i)
    {
        CHECK (dyn[i].note == 57);
        CHECK (dyn[i].value == velocities[i]);
    }

    const auto reg = notesOn (fixtures::registerSweep (50));
    REQUIRE (reg.size() == 5);
    const int offsets[] = { -24, -12, 0, 12, 24 };
    for (std::size_t i = 0; i < 5; ++i)
        CHECK (reg[i].note == 50 + offsets[i]);

    const auto hold = fixtures::longHold (60);
    CHECK (hold.endTimeSeconds() == Approx (60.0));
    CHECK (notesOn (hold).size() == 1);

    const auto chord = fixtures::longChord (60);
    CHECK (chord.endTimeSeconds() == Approx (60.0));
    CHECK (notesOn (chord).size() == 4);

    const auto sustains = notesOn (fixtures::repeatedSustains (60));
    CHECK (sustains.size() == 5);

    // Melody covers steps, thirds, fourth/fifth, repetition and velocity variation.
    const auto mel = notesOn (fixtures::melody (60));
    std::set<int> intervals;
    std::set<int> vels;
    bool repeated = false;
    for (std::size_t i = 1; i < mel.size(); ++i)
    {
        intervals.insert (std::abs (mel[i].note - mel[i - 1].note));
        repeated = repeated || mel[i].note == mel[i - 1].note;
        vels.insert (mel[i].value);
    }
    CHECK (intervals.count (2));
    CHECK ((intervals.count (3) || intervals.count (4)));
    CHECK ((intervals.count (5) || intervals.count (7)));
    CHECK (repeated);
    CHECK (vels.size() >= 4);

    const auto chords = fixtures::chords (60);
    CHECK (notesOn (chords).size() == 3 + 3 + 3 + 4 + 4);

    // Note-offs precede note-ons at equal times.
    for (const auto& name : fixtures::allNames())
    {
        const auto seq = fixtures::byName (name, 60);
        REQUIRE (seq);
        for (std::size_t i = 1; i < seq->events.size(); ++i)
            REQUIRE (seq->events[i - 1].timeSeconds <= seq->events[i].timeSeconds);
    }
}

TEST_CASE ("fixtures: profiles", "[unit][midi]")
{
    CHECK (fixtures::profile ("quick").value() == std::vector<std::string> { "repetition", "register" });
    CHECK (fixtures::profile ("standard").value().size() == 5);
    CHECK (fixtures::profile ("sustain").value() == std::vector<std::string> { "long-hold", "long-chord", "repeated-sustains" });
    CHECK (fixtures::profile ("full").value().size() == fixtures::allNames().size());
    CHECK_FALSE (fixtures::profile ("everything").has_value());
    CHECK_FALSE (fixtures::byName ("nope", 60).has_value());
}

TEST_CASE ("MIDI files: written fixtures read back with exact timing", "[unit][midi]")
{
    test::TempDir dir;
    std::vector<std::string> written;
    std::string error;
    REQUIRE (research::writeFixtureFiles (dir.path(), written, error));
    REQUIRE (written.size() == fixtures::allNames().size());

    for (const auto& name : fixtures::allNames())
    {
        const auto original = *fixtures::byName (name, 60);
        const auto loaded = io::readMidiFile (dir / (name + ".mid"), error);
        REQUIRE (loaded);
        REQUIRE (loaded->events.size() == original.events.size());
        for (std::size_t i = 0; i < original.events.size(); ++i)
        {
            CHECK (loaded->events[i].type == original.events[i].type);
            CHECK (loaded->events[i].note == original.events[i].note);
            CHECK (loaded->events[i].timeSeconds == Approx (original.events[i].timeSeconds).margin (1e-6));
            if (original.events[i].type == MidiEvent::Type::noteOn)
                CHECK (loaded->events[i].value == original.events[i].value);
        }
    }

    CHECK_FALSE (io::readMidiFile (dir / "missing.mid", error));
}

TEST_CASE ("MIDI files: committed fixtures match the generators", "[unit][midi]")
{
    // research/midi/*.mid are generated by `research-renderer --write-fixtures research/midi`.
    for (const auto& name : fixtures::allNames())
    {
        std::string error;
        const auto loaded = io::readMidiFile (std::filesystem::path (OSP_SOURCE_DIR) / "research" / "midi" / (name + ".mid"), error);
        INFO (name << ": " << error);
        REQUIRE (loaded);
        const auto original = *fixtures::byName (name, 60);
        REQUIRE (loaded->events.size() == original.events.size());
        for (std::size_t i = 0; i < original.events.size(); ++i)
            CHECK (loaded->events[i].timeSeconds == Approx (original.events[i].timeSeconds).margin (1e-6));
    }
}
